# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Missive Help Centre
description: > # this means to ignore newlines until "baseurl:"
  This is the documentation for the Missive form-to-email service.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://missive-test.jondh.me.uk" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
